name: auth_repository
description: The authentication and its abstraction of the points project
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  supabase:
    git: https://github.com/bit-burger/supabase-dart
  hive: ^2.0.4

dev_dependencies:
  test: ^1.19.3

  supabase_testing_utils:
    path: ../supabase_testing_utils

  # Mocking and faking
  faker: ^2.0.0
  hive_test:
    path: ../hive_test
