name: points
description: An example social media app, written in dart with Flutter and supabase as a backend
publish_to: none

version: 0.0.1

environment:
  sdk: ">=2.12.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Configuration
  flutter_dotenv: ^5.0.2

  # UI
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.3
  ionicons: ^0.1.2
  adaptive_dialog: ^1.1.0
  flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git

  # Supabase
  supabase_flutter: ^0.2.8
  hive_flutter: ^1.1.0

  # State management
  flutter_bloc: ^7.3.1
  bloc: ^7.2.1
  provider: ^6.0.1

  # Own packages
  auth_repository:
    path: ./auth_repository
  points_repositories:
    path: ./points_repositories

dev_dependencies:
  # Test framework
  flutter_test:
    sdk: flutter
  bloc_test: ^8.3.0

  # Raw packages (without Flutter)
  supabase: ^0.2.8
  hive: ^2.0.4

  # Mocking and faking
  faker: ^2.0.0

flutter:
  assets:
    - .env
    - google_fonts/
#  fonts:
#    - family: Courier Prime
#      fonts:
#        - asset: assets/fonts/courier_prime/CourierPrime-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/courier_prime/CourierPrime-BoldItalic.ttf
#          weight: 700
#          style: italic
#        - asset: assets/fonts/courier_prime/CourierPrime-Regular.ttf
#          weight: 500
#        - asset: assets/fonts/courier_prime/CourierPrime-Regular.ttf
#          weight: 500
#          style: italic

  uses-material-design: true