name: points
description: An example social media app, written in dart with Flutter and supabase as a backend
publish_to: none

version: 0.0.1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  # Flutter and extensions
  flutter:
    sdk: flutter
  flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git

  # Icons and fonts
  cupertino_icons: ^1.0.4
  google_fonts: ^2.1.0
  ionicons: ^0.1.2

  # Widgets
  adaptive_dialog: ^1.2.0
  infinite_scroll_pagination: ^3.1.0

  # State management
  flutter_bloc: ^7.3.3
  bloc: ^7.2.1
  provider: ^6.0.1

  # Configuration
  flutter_dotenv: ^5.0.2

  # Supabase
  supabase_flutter: ^0.2.9
  hive_flutter: ^1.1.0

  # Own packages
  auth_repository:
    path: ./packages/auth_repository
  user_repositories:
    path: ./packages/user_repositories

dev_dependencies:
  # Test framework
  bloc_test: ^8.5.0
  flutter_test:
    sdk: flutter

  # Raw packages (without Flutter)
  supabase: ^0.2.9
  hive: ^2.0.4

  # Mocking and faking
  faker: ^2.0.0
  mocktail: ^0.2.0

flutter:
  assets:
    - .env
    - google_fonts/

  uses-material-design: true