name: points
description: An example social media app, written in dart with Flutter and supabase as a backend
publish_to: none

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Configuration
  flutter_dotenv: ^5.0.2

  # UI
  cupertino_icons: ^1.0.3
  flutter_neumorphic: ^3.1.0

  # Supabase
  supabase_flutter: ^0.2.8
  hive_flutter: ^1.1.0

  # State management
  flutter_bloc: ^7.3.0
  bloc: ^7.2.1
  provider: ^6.0.1

  # Own packages
  auth_repository:
    path: ./auth_repository
  points_repository:
    path: ./points_repository

dev_dependencies:
  test: ^1.17.12
  matcher: ^0.12.11

flutter:
  assets:
    - .env
  uses-material-design: true