name: notification_repository
description: The repository to handle and listen to notifications of points
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  supabase:
    git: https://github.com/bit-burger/supabase-dart

dev_dependencies:
  test: ^1.16.0
  supabase_testing_utils:
    path: ../supabase_testing_utils