name: meta_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  supabase: ^0.2.10

dev_dependencies:
  test: ^1.16.0
