name: supabase_testing_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  supabase:
    git: https://github.com/offline-first/supabase-dart
  dotenv: ^3.0.0
  faker: ^2.0.0
  hive_test:
    path: ../hive_test
  auth_repository:
    path: ../auth_repository
  user_repositories:
    path: ../user_repositories